### PR TITLE
Compatibility with 1.2.x

### PR DESCRIPTION
**Pull request by praseodym**
- In 1.2.0, some properties were renamed. We change them in this project too.
- Change server port to 8081 to allow OIDC server to be ran on 8080.
- Cleanup unused schemas in Spring XML config files.
- Print object contents on user.jsp (e.g. address claim).

### CODE REVIEW

**Comment by jricher** [comment]
Thanks for pulling this together. I usually run simple-web-app in the same Tomcat container instance along side the server, so I'd prefer to keep the example on :8080. I understand that if you're running it as a separate Jetty instance or something similar, that can be problematic, but I'm not sure of a good way to handle both cases simultaneously from one demo app.

**Comment by praseodym** [comment]
I see. I'll check if we can make it so that the port number is easier to change.

**Comment by praseodym** [comment]
I've updated the PR. Server port is now kept at 8080, but I configured the URLs using an inline properties definition so that they only need to be changed in one place.

**Comment by jricher** [comment]
I can see what you're doing here, but the one thing I don't like about this setup is that it gives the impression that a server's URLs need to follow the same pattern that the MITREid Connect server uses. This very issue has tripped up some junior developers in the past, and so we went with plain strings everywhere in the simple-web-app demo client config file. Let me rethink this position though, thanks.

**Pull request closed without merging**
